version: '2'

services:
    app:
        build:
            context: app
        # ports:
        #     - "3000:3000"
        expose:
            - 3000
        scale: 1

    svc:
        image: arqsoft/bbox:202201.1
        volumes:
            - "./svc/config.properties:/opt/bbox/config.properties"

    nginx:
        image: nginx:1.21.6
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            # - ./nginx_reverse_proxy_replicated.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - app

    graphite:
        image: graphiteapp/graphite-statsd:1.1.8-8
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:8.4.6
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.44.0
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local
